name = "Nexus of Origins-1.2.11"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4a5564b648ea160428cfbdd7b8999b1b5fa2b31fd8571ebd1bd1b2d8f77450f"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"
