name = "Nexus of Origins-1.2.11"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e28dce9e1663d192c089af89a0eac4c7de145047bd6fbec42e81b542b1c6fb04"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"
