name = "Nexus of Origins-1.2.11"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "924fa3c159d1d286d15899cc2ee1aab7a41745af509e6b92278dad8a050d6430"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"
